# The URL the site will be built for
base_url = "https://lijunzh.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Enable RSS feed generation
generate_feeds = true

# Specify the feed filenames (you can use either or both)
feed_filenames = ["rss.xml", "atom.xml"]

theme = "papermod"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "one-dark"

[search]
index_format = "elasticlunr_json"

title = "Lijun Zhu"
description = "Tech leadership insights, AI innovation, and team building expertise from a Director of Computer Vision"

[extra]
# Put all your custom variables here
author = "Lijun Zhu"

# PaperMod theme configuration
[extra.papermod]
title = "Lijun Zhu"
default_theme = "auto"
theme = "light"
language_direction = "ltr"
keywords = ["tech leadership", "AI", "computer vision", "machine learning", "team building", "engineering management", "technology innovation"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
date_format = "%Y-%m-%d"

home_title = "Lijun Zhu"
home_content = """
<div style="display: flex; align-items: center; gap: 3rem; margin: 3rem 0; max-width: 800px; margin-left: auto; margin-right: auto; flex-wrap: wrap; justify-content: center;">
    <div style="flex-shrink: 0;">
        <div style="width: 200px; height: 200px; border-radius: 50%; overflow: hidden; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
            {{ resize_image(path="images/lijun.jpg", width=200, height=200, op="fill", alt="Lijun Profile Picture") }}
        </div>
    </div>
    <div style="flex: 1; min-width: 300px; text-align: left; position: relative;">
        <div style="font-size: 1.6rem; font-weight: 300; line-height: 1.5; color: var(--primary); font-style: italic; position: relative;">
            <span style="font-size: 2rem; color: var(--secondary); opacity: 0.6; position: absolute; left: -1rem; top: -0.5rem;">"</span>
            Leading teams to achieve full potential.
            <span style="font-size: 2rem; color: var(--secondary); opacity: 0.6; position: absolute; right: -1rem; bottom: -0.5rem;">"</span>
        </div>
        <div style="width: 60px; height: 2px; background: var(--primary); margin: 1.5rem 0 0 0; opacity: 0.7;"></div>
    </div>
</div>

I helped building effective teams at organizations like <a href="https://tech.walmart.com/content/walmart-global-tech/en_us.html" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">Walmart Global Tech</a>, <a href="https://www.ti.com/" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">Texas Instruments</a>, and <a href="https://www.gatech.edu/" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">Georgia Institute of Technology</a>. 



<div style="margin-top: 4rem;"></div>

## A brief history

<div style="margin: 2rem 0;">
    <div style="display: grid; gap: 1.5rem; max-width: 800px; margin: 0 auto;">
        <div class="timeline-card timeline-card-1" style="display: grid; grid-template-columns: 100px 1fr; gap: 1rem; padding: 1.5rem; background-color: var(--entry); border-radius: 8px;">
            <div class="timeline-date" style="font-weight: 600; font-size: 0.9rem;">2025-now</div>
            <div>
                <div style="font-weight: 600; margin-bottom: 0.5rem;">Director of Computer Vision</div>
                <div style="color: var(--secondary);"><a href="https://tech.walmart.com/content/walmart-global-tech/en_us.html" style="color: var(--primary); text-decoration: none;">Walmart Global Tech</a></div>
            </div>
        </div>
        <div class="timeline-card timeline-card-2" style="display: grid; grid-template-columns: 100px 1fr; gap: 1rem; padding: 1.5rem; background-color: var(--entry); border-radius: 8px;">
            <div class="timeline-date" style="font-weight: 600; font-size: 0.9rem;">2022-2025</div>
            <div>
                <div style="font-weight: 600; margin-bottom: 0.5rem;">Manager of Machine Learning</div>
                <div style="color: var(--secondary);"><a href="https://tech.walmart.com/content/walmart-global-tech/en_us.html" style="color: var(--primary); text-decoration: none;">Walmart Global Tech</a></div>
            </div>
        </div>
        <div class="timeline-card timeline-card-3" style="display: grid; grid-template-columns: 100px 1fr; gap: 1rem; padding: 1.5rem; background-color: var(--entry); border-radius: 8px;">
            <div class="timeline-date" style="font-weight: 600; font-size: 0.9rem;">2018-2022</div>
            <div>
                <div style="font-weight: 600; margin-bottom: 0.5rem;">Team lead of Machine Learning</div>
                <div style="color: var(--secondary);"><a href="https://www.ti.com/technologies/edge-ai.html" style="color: var(--primary); text-decoration: none;">Texas Instruments</a></div>
            </div>
        </div>
        <div class="timeline-card timeline-card-4" style="display: grid; grid-template-columns: 100px 1fr; gap: 1rem; padding: 1.5rem; background-color: var(--entry); border-radius: 8px;">
            <div class="timeline-date" style="font-weight: 600; font-size: 0.9rem;">2013-2018</div>
            <div>
                <div style="font-weight: 600; margin-bottom: 0.5rem;">Lead Research Assistant</div>
                <div style="color: var(--secondary);"><a href="https://cegp.ece.gatech.edu/" style="color: var(--primary); text-decoration: none;">Georgia Institute of Technology</a></div>
            </div>
        </div>
    </div>
</div>

## My work

<div style="margin-top: 2rem;"></div>

As Director of Computer Vision at <a href="https://tech.walmart.com/content/walmart-global-tech/en_us.html" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">Walmart Global Tech</a>, I've led high-performing teams to deliver cutting-edge AI solutions, scaling machine learning initiatives that drive business impact. With experience building effective engineering organizations at <a href="https://www.ti.com/" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">Texas Instruments</a> and <a href="https://www.gatech.edu/" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">Georgia Tech</a>, I specialize in fostering innovation, talent development, and cross-functional collaboration in fast-paced tech environments. As an open-source contributor to projects like <a href="https://numpy.org/" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">NumPy</a>, <a href="https://github.com/obspy/obspy" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">ObsPy</a>, and <a href="https://pytorch.org/" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px;">PyTorch</a>, I'm passionate about advancing AI technologies—let's connect to explore leadership opportunities.

<div style="text-align: center; margin: 2rem 0;">
    <p style="font-size: 1.2rem; font-weight: 300; line-height: 1.6; color: var(--secondary); font-style: italic; max-width: 700px; margin: 0 auto;">"Platforms can be more than functional - they can inspire our thinking and enable us to do things that we didn't know we could before."</p>
</div>

## A bit about me

<div style="margin-top: 2rem;"></div>

I like to read, I play instruments, I love to BBQ, and even though I can no longer spend significant time to do it, I can't stop coding.

<div style="text-align: center; margin: 2rem 0;">
    <p style="font-size: 1.2rem; font-weight: 300; line-height: 1.6; color: var(--secondary); font-style: italic; max-width: 700px; margin: 0 auto;">"Learning is my great passion and curiosity is my ultimate drive."</p>
</div>

<div style="text-align: center; margin: 1rem 0 3rem 0;">
    <a href="/about" style="color: var(--secondary); text-decoration: underline; text-decoration-color: var(--border); text-underline-offset: 2px; font-weight: 500;">Learn more about me →</a>
</div>
"""

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/about", title = "About" },
    { url = "$BASE_URL/posts", title = "Posts" },
    { url = "$BASE_URL/search", title = "Search" },
]

social_icons = [
    { url = "https://github.com/lijunzh/resume/releases/latest/download/resume.pdf", title = "Resume", icon = "cv" },
    { url = "mailto:gatechzhu@gmail.com", title = "Email", icon = "email" },
    { url = "https://github.com/lijunzh/", title = "GitHub", icon = "github" },
    { url = "https://www.linkedin.com/in/lijunzh/", title = "LinkedIn", icon = "linkedin" },
    { url = "$BASE_URL/rss.xml", title = "RSS", icon = "rss" },
]
